# Created using wingetcreate 1.5.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.5.0.schema.json

PackageIdentifier: StefansTools.grepWin
PackageVersion: 2.0.1232
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.5.0
